# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # renovate: datasource=docker packageName=ghcr.io/home-assistant/aarch64-base:3.21
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  # aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"

labels:
  org.opencontainers.image.title: "Waterfurnace-Aurora"
  org.opencontainers.image.description: "Add-on that run the waterfurnace-aurora service to interface with your geothermal heatpump."
  org.opencontainers.image.source: "https://github.com/mdallaire/hass-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2024.11.2"
