# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Waterfurnace-Aurora
version: "v1.5.7-1"
slug: waterfurnace
description: Add-on that run the waterfurnace aurora ruby gem to interface with your geothermal heatpump.
url: "https://github.com/mdallaire/hass-addons/waterfurnace"
arch:
  # - aarch64
  - amd64
init: false
apparmor: false
uart: true
services:
  - mqtt:need
options:
  tty: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0LICHU-if00-port0
schema:
  tty: "str"
  mqtt: "str?"
image: "ghcr.io/mdallaire/{arch}-addon-waterfurnace-aurora"
